# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9e2ad75f8cd301df9c4c770ac47579464172d05d88ec7f0c5a050884b321adf843b2f33c3c0776689a8978cbf4f7963bd1d307870423be311ecedba4e191553

test:
  secret_key_base: 12759866d8d9b1206451b4f53c65b038140db7acbe1824bdb342ae83a02acdb3b377172e67eea09af9113bd2f9a7daf8634926d8317a6c9d3cb14cc5288919c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
